import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.scss";
import "../styles/base.scss";
import { ThemeProvider } from "next-themes";
import { ToastProvider } from "@/components/toastProvider/toastProvider";
import { ClientProvider } from "@/components/clientProvider/clientProvider";

export const metadata: Metadata = {
  title: "AI Job Pilot",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <ClientProvider>{children}</ClientProvider>
          <ToastProvider />
        </ThemeProvider>
      </body>
    </html>
  );
}
